version: '3.8'
services:
  db:
    image: postgres:13
    container_name: hotel_reservation_db
    environment:
      POSTGRES_DB: HotelReservation
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - hotel_reservation_data:/var/lib/postgresql/data

volumes:
  hotel_reservation_data: